// Code generated by Slice Machine. DO NOT EDIT.

import CallToAction from './CallToAction';
import Footer from './Footer';
import Header from './Header';
import HeroSlice from './HeroSlice';
import ImageGrid from './ImageGrid';

export {
	CallToAction,
	Footer,
	Header,
	HeroSlice,
	ImageGrid,
};

export const components = {
	call_to_action: CallToAction,
	footer: Footer,
	header: Header,
	hero_slice: HeroSlice,
	image_grid: ImageGrid,
};
