// Code generated by Slice Machine. DO NOT EDIT.

import CallToAction from './CallToAction';
import HeroSlice from './HeroSlice';
import ImageGrid from './ImageGrid';

export {
	CallToAction,
	HeroSlice,
	ImageGrid,
};

export const components = {
	call_to_action: CallToAction,
	hero_slice: HeroSlice,
	image_grid: ImageGrid,
};
